### ISSUE TITLE
Pagination highlighted index

### ISSUE THREAD

**Issue by chanceaclark** [bigcommerce/big-design#512]
**Describe the bug**
The correct range of the `Pagination` component should be highlighted instead of it always being the first item.

**Screenshots**
As you can see here I selected the second range (`range[1]`) but the first item is highlighted.

![Screen Shot 2021-03-15 at 15 58 01](https://user-images.githubusercontent.com/10539418/111220685-7ee68000-85a7-11eb-9770-064facfc8827.png)

**Comment by jorgemoya** [comment]
The expected behavior for a dropdown is to auto select the first option `onOpen`. This behavior is weird because it is a button that changes value depending on the dropdown selection/click, kind of like a select. Not sure what the correct path is for this, I could add a boolean prop that allows dropdown to track last clicked item. Is this something we need?
