### ISSUE TITLE
Datepicker component doesn't support manual text entry

### ISSUE THREAD

**Issue by bobbyshaw** [bigcommerce/big-design#525]
**Describe the bug**

The datepicker component does not support manual edits to the input text field despite the underlying library appearing to support this.

 e.g. change 04/10/2021 to 04/11/2021 and the following error occurs, `RangeError locale must contain match property`

**To Reproduce**

See code sandbox example https://codesandbox.io/s/affectionate-knuth-rrhp4?file=/src/index.tsx 

1. Choose a date in the React Datepicker example
2. Modify the input to change the day
3. Date is updated. 
4. Choose a date in the Bigcommerce Datepicker example
5. Modify the input to change the day.
6. Error occurs

It can also be reproduce on https://developer.bigcommerce.com/big-design/datepicker

**Expected behavior**
Manual text editing of resulting date in input field is supported. 

**Screenshots**

<img width="1188" alt="Screenshot 2021-04-22 at 20 33 56" src="https://user-images.githubusercontent.com/553566/115775423-c59b7700-a3aa-11eb-8e02-4b4bbbb5c514.png">
<img width="1184" alt="Screenshot 2021-04-22 at 20 34 11" src="https://user-images.githubusercontent.com/553566/115775425-c6cca400-a3aa-11eb-8554-e8cb50c778a5.png">
<img width="1064" alt="Screenshot 2021-04-22 at 20 38 30" src="https://user-images.githubusercontent.com/553566/115775430-c7fdd100-a3aa-11eb-9640-ddbaaba5df78.png">

**Additional Comments**

I haven't immediately been able to see the cause of the problem but I did wonder if this is a side effect of converting dates to strings in the BigCommerce component. See: https://github.com/bigcommerce/big-design/blame/0b863febebb80a9570b79eeda23e4caed5893119/packages/big-design/src/components/Datepicker/Datepicker.tsx#L43-L51

What was the reason for changing the value/startDate prop to be of type string rather than date?

**Comment by chanceaclark** [comment]
Hey @bobbyshaw thanks for noting this! @animesh1987 will take a look at this and let you know his findings.

**Comment by animesh1987** [comment]
Hey @bobbyshaw thanks for the detailed information regarding the issue. 

The issue occurs due to missing `match` property in locale object. The underlying library uses DateFns's `parse` method to return a parsed date from the string provided using the given date format. Parse method expects `locale` to have a match property. This method is only called when a user tries to manually edit the date. 

We will work on adding a `match` property with all the underlying methods to locale object which should resolve the issue.

We change the value/startDate to be a type of string so we can adhere to https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/date standards.

Thanks again and please feel free to ask any more questions.

**Comment by bobbyshaw** [comment]
Thanks for investigating so quickly, Animesh. That all make sense to me.

**Comment by thangpham-wz** [comment]
Hi guys, any updates on this? 

I got into the same issues and it throws error directly into the console. 🤔

**Comment by chanceaclark** [comment]
Fixed in https://github.com/bigcommerce/big-design/pull/575
